Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/*/**.rb'
Metrics/PerceivedComplexity:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 15
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
